version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    network_mode: "host"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=5001
    restart: unless-stopped
